
endpoint.apple: https://swa.apple.com/api/v1.0/external

server:
  port: 9001
  ssl:
    enabled: false
    client-auth: need
    key-store: classpath:bagid.jks
    key-store-password: <password>
    key-alias: from-apple
    key-store-type: PKCS12
    key-store-provider: SUN
    trust-store: classpath:cacerts
    trust-store-password: changeit
    trust-store-type: JKS
    trust-store-provider: SUN

spring:
  application:
    name: nt-ms